### ISSUE TITLE
Use Promises?

### ISSUE THREAD

**Issue by piranna** [direktspeed/node-fuse-bindings#5]
We would need to discuss if we want to use Promises in the API, or just only fix it so use standand Node.js errbacks and wrap them in userland with `util.promisify`. Probably the second option is better since it's an API fix instead of a rewrite, just only being this a fork could allow to do this kind of things.

**Comment by piranna** [comment]
More info about the API fixes at https://github.com/mafintosh/fuse-bindings/issues/10

**Comment by frank-dspeed** [comment]
ok just my 5 cents i love promises my self but i don't want to break existing implamentations that are using the current api so if you want to use Promises do it like the fs module did it

```
fs.promises
```

i really want to keep the existing implamentations as they are used in many other projects the main goal of this fork is that it is still use able with current nodejs versions.

**Comment by piranna** [comment]
Yes, I agree on that, just only my main concern is about fixing the API issues, like the one described in https://github.com/mafintosh/fuse-bindings/issues/10. Besides that, I'm ok with using callbacks.

**Comment by frank-dspeed** [comment]
@piranna i think that fuse-nativ will be ready in some month its not worth the effort to fix that as we will merge that with a compatible api to the existing that is then the final step all ongoing work will end in fuse-nativ

**Comment by piranna** [comment]
If that's the long term intention, then I'll open an issue there to fix that. Thanks! :-)

**Comment by piranna** [comment]
I've review the `fuse-native` code and seems all operations callbacks are correct errbacks, so this would not happen. I'm going to close this. Thanks! :-D
